CREATE TABLE Client (
    ClientID INT IDENTITY PRIMARY KEY,
    ClientName NVARCHAR(255) NOT NULL
)

CREATE TABLE Brand (
    BrandID INT IDENTITY PRIMARY KEY,
    Brand NVARCHAR (255) NOT NULL,
    HGAM NVARCHAR(255) NOT NULL,
    Contact NVARCHAR(255) NOT NUll,
    ClientID INT FOREIGN KEY REFERENCES Client(ClientID)
)

CREATE TABLE Item (
    ItemID INT IDENTITY PRIMARY KEY,
    Alias NVARCHAR(255) NOT NULL,
    Sku NVARCHAR(255) NOT NULL,
    SizeOZ DECIMAL(10,2) NOT NULL,
    ItemGroup NVARCHAR(255) NOT NULL,
    Category NVARCHAR(255) NOT NULL,
    BrandID INT FOREIGN KEY REFERENCES Brand(BrandID)
)

CREATE TABLE Dates (
    WMWeek CHAR(6) PRIMARY KEY,
    WeekStart DATETIME NOT NULL,
    FiscalYear CHAR(4) NOT NULL,
    Month NVARCHAR(20) NOT NULL,
    Season NVARCHAR(25) NOT NULL
)

CREATE TABLE Historical (
    WMWeek CHAR(6) FOREIGN KEY REFERENCES Dates(WMWeek),
    ItemID INT FOREIGN KEY REFERENCES Item(ItemID),
    UnitCost DECIMAL(10,2) NOT NULL,
    StoreCount INT NOT NULL,
    POSQuantity INT NOT NULL,
    PRIMARY KEY (WMWeek, ItemID)
);

