CREATE TABLE Client (
    ClientID INT IDENTITY PRIMARY KEY,
    ClientName NVARCHAR(255) NOT NULL
)

CREATE TABLE Brand (
    BrandID INT IDENTITY PRIMARY KEY,
    Brand NVARCHAR (255) NOT NULL,
    HGAM NVARCHAR(255) NOT NULL,
    Contact NVARCHAR(255) NOT NUll,
    ClientID INT FOREIGN KEY REFERENCES Client(ClientID)
)

CREATE TABLE Item (
    ItemID INT IDENTITY PRIMARY KEY,
    Alias NVARCHAR(255) NOT NULL,
    Sku NVARCHAR(255) NOT NULL,
    SizeOZ DECIMAL(10,2) NOT NULL,
    ItemGroup NVARCHAR(255) NOT NULL,
    Category NVARCHAR(255) NOT NULL,
    BrandID INT FOREIGN KEY REFERENCES Brand(BrandID)
)

CREATE TABLE WM_Date (
    WMWeek CHAR(6) PRIMARY KEY,
    WeekStart DATETIME NOT NULL,
    FiscalYear CHAR(4) NOT NULL,
    Month NVARCHAR(20) NOT NULL,
    Season NVARCHAR(25) NOT NULL
)

CREATE TABLE Forecast_Profile (
    ProfileID INT IDENTITY PRIMARY KEY,
    ProfileName NVARCHAR(25) NOT NULL,
    Multiplier DECIMAL(5,2) NOT NULL DEFAULT 1,
    IsDefaultProfile BINARY NOT NULL,
    LeadTime INT NOT NULL
)

CREATE TABLE Use_Profile (
    ItemID INT FOREIGN KEY REFERENCES Item(ItemID),
    ProfileID INT FOREIGN KEY REFERENCES Forecast_Profile(ProfileID),
    StartWeek CHAR(6) FOREIGN KEY REFERENCES Dates(WMWeek),
    FinalWeek CHAR(6) FOREIGN KEY REFERENCES Dates(WMWeek),
    PRIMARY KEY (ItemID, StartWeek, FinalWeek)
)

CREATE TABLE Historical (
    WMWeek CHAR(6) FOREIGN KEY REFERENCES WM_Date(WMWeek),
    ItemID INT FOREIGN KEY REFERENCES Item(ItemID),
    UnitCost DECIMAL(10,2) NOT NULL,
    StoreCount INT NOT NULL,
    POSQuantity INT NOT NULL,
    PRIMARY KEY (WMWeek, ItemID)
);

