CREATE TABLE Client
(
    ClientID INT IDENTITY PRIMARY KEY,
    ClientName VARCHAR(100) NOT NULL
)

CREATE TABLE Brand
(
    BrandID INT IDENTITY PRIMARY KEY,
    BrandName VARCHAR (100) NOT NULL,
    ClientID INT FOREIGN KEY REFERENCES Client(ClientID)
)

CREATE TABLE ProductCategory
(
    CatID INT IDENTITY PRIMARY KEY,
    CatName VARCHAR (100) NOT NULL
)

CREATE TABLE ProductGroup
(
    GroupID INT IDENTITY PRIMARY KEY,
    GroupName VARCHAR (100) NOT NULL
)

CREATE TABLE Item
(
    ItemID INT IDENTITY PRIMARY KEY,
    ItemName NVARCHAR(100) NOT NULL,
    BrandID INT FOREIGN KEY REFERENCES Brand(BrandID),
    CatID INT FOREIGN KEY REFERENCES ProductCategory(CatID),
    GroupID INT FOREIGN KEY REFERENCES ProductGroup(GroupID)
)

CREATE TABLE WMWeek
(
    WMWeekCode INT PRIMARY KEY,
    WM_WeekNum INT NOT NULL,
    WM_Year CHAR(4) NOT NULL,
    WM_Month INT,
    CalStartDate DATETIME NOT NULL,
    CHECK (WM_WeekNum > 0 AND WM_WeekNum <= 53),
    CHECK (WM_Month > 0 AND WM_Month <= 12)
)

CREATE TABLE Historical
(
    HistoricalID INT IDENTITY PRIMARY KEY,
    WMWeekCode INT FOREIGN KEY REFERENCES WMWeek(WMWeekCode) NOT NULL,
    ItemID INT FOREIGN KEY REFERENCES Item(ItemID) NOT NULL,
    ItemPrice DECIMAL(6,2) NOT NULL,
    POS_Stores INT NOT NULL,
    POS_Items INT NOT NULL,
    CHECK (POS_Stores >= 0),
    CHECK (POS_Items >= 0)
)

CREATE TABLE ProfileData
(
    DataID INT IDENTITY PRIMARY KEY,
    ProfileID INT FOREIGN KEY REFERENCES SeasonalProfile(ProfileID),
    WeekNum INT NOT NULL,
    SeasonFactor DECIMAL(3,1) NOT NULL
)

CREATE TABLE Forecast
(
    ForecastID INT IDENTITY PRIMARY KEY,
    ItemID INT FOREIGN KEY REFERENCES Item(ItemID) DEFAULT NULL,
    WMWeekCode INT FOREIGN KEY REFERENCES WMWeek(WMWeekCode) NOT NULL,
    Velocity DECIMAL(3,1) NOT NULL,
    ForecastPrice DECIMAL(15,2) DEFAULT 1.00,
    ForecastStores INT DEFAULT 0,
    ItemAdjust INT NOT NULL DEFAULT 0,
    FactorAdjust DECIMAL(3,1) NOT NULL DEFAULT 1,
    LeadTime INT
);


